export const mockArticles = [
  {
    id: 1,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn React',
    categoryId: 3,
    userId: 1,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: '',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 2,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 3,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 4,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 5,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 6,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 7,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 8,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 9,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 10,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 11,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
  {
    id: 12,
    picture: 'https://ortodonta.com/wp-content/uploads/2021/03/girl-919048__340.jpg',
    title: 'I learn Node',
    categoryId: 3,
    userId: 2,
    category: {
      id: 1,
      title: 'finance',
      url: 'finance',
      createdAt: '2020-03-03T12:00:00.000Z',
      updatedAt: '2020-03-03T12:00:00.000Z',
    },
    coverImage: '',
    views: 10,
    url: '#',
    _count: { comments: 25 },
    spoiler:
      'consectetur adipiscing elit. Ut sagittist at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sagittis, sem quis commodo malesuada, erat arcu ornare leo, ut volutpat metus erat at tellus. Maecenas metus tellus, rutrum porta condimentum id, lobortis vel dui. Vestibulum venenatis tincidunt porttitor. Vivamus tempor pharetra tellus, ac lacinia felis.',
    content: 'Maecenas metus tellus',
    createdAt: '2020-03-03T12:00:00.000Z',
    updatedAt: '2020-08-03T12:00:00.000Z',
  },
];
